# Log level
sonar.log.level=DEBUG

# Encryption
sonar.secretKeyPath=./conf/sonar-secret.txt

# Update Center
sonar.updatecenter.activate=false

# Embedded Tomcat
sonar.web.accessLogs.pattern=%h %l %reqAttribute{LOGIN} [%t] '%r' %s %b '%i{Referer}' '%i{User-Agent}' '%reqAttribute{ID}'
sonar.web.systemPasscode={aes-gcm}pE2kwwm9ZQwDB/3iKpg0UlQK12BXB/vs3Vi6997lHqX9Bw==
